version: 0.2

env:
  shell: bash
  variables:
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "true"
    DOTNET_SYSTEM_GLOBALIZATION_PREDEFINED_CULTURES_ONLY: "false"
    DOTNET_NOLOGO: "true"
    CONFIGURATION: "Release"

phases:
  install:
    runtime-versions:
      docker: 19

    commands:
      - dotnet-install.sh --jsonfile global.json
      - dotnet --info

  pre_build:
    commands:
      - . ./scripts/codebuild-extras.sh

  build:
    commands:
      - dotnet restore
      - dotnet publish --no-restore
      - dotnet test --logger trx --no-build

      - ./scripts/create-config-files.sh

  post_build:
    commands:
      - ./scripts/package-template.sh

artifacts:
  discard-paths: yes
  files:
    - "bin/identity-resources.template.yml"
    - "identity-resources.*.config.json"

reports:
  test-results:
    files:
      - "**/TestResults/*.trx"
    discard-paths: yes
    file-format: VisualStudioTrx
