Description: Custom Resources for Brighid Identity.
Transform: AWS::Serverless-2016-10-31
Parameters:
  LambdajectionVersion:
    Type: String
    Description: Version of Lambdajection to use.

  DotnetVersion:
    Type: String
    Description: Version of .NET to use.

  IdentityServerUri:
    Type: String
    Description: URI of the identity server.

  IdentityClientId:
    Type: String
    Description: Client ID of the Discord Application.

  IdentityClientSecret:
    Type: String
    Description: Encrypted Client Secret of the Discord Application.

Resources:
  ApplicationResource:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Brighid.Identity.Resources.Application::Brighid.Identity.Resources.Application.Handler::Run
      Runtime: provided.al2
      Timeout: 30
      CodeUri: ../bin/Resources.Application/Release/linux-x64/publish/
      MemorySize: 512
      Policies:
        - !ImportValue cfn-utilities:SecretsKeyDecryptPolicyArn
      Layers:
        - !Sub "{{resolve:ssm:/dotnet/${DotnetVersion}/layer-arn}}"
        - !Sub "{{resolve:ssm:/lambdajection/${LambdajectionVersion}/layer-arn}}"
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue cfn-utilities:LambdaSecurityGroupId
        SubnetIds: !Split [",", !ImportValue cfn-utilities:SubnetIds]
      Environment:
        Variables:
          Identity__IdentityServerUri: !Ref IdentityServerUri
          Identity__ClientId: !Ref IdentityClientId
          Identity__ClientSecret: !Ref IdentityClientSecret

  RoleResource:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Brighid.Identity.Resources.Role::Brighid.Identity.Resources.Role.Handler::Run
      Runtime: provided.al2
      Timeout: 30
      CodeUri: ../bin/Resources.Role/Release/linux-x64/publish/
      MemorySize: 512
      Policies:
        - !ImportValue cfn-utilities:SecretsKeyDecryptPolicyArn
      Layers:
        - !Sub "{{resolve:ssm:/dotnet/${DotnetVersion}/layer-arn}}"
        - !Sub "{{resolve:ssm:/lambdajection/${LambdajectionVersion}/layer-arn}}"
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue cfn-utilities:LambdaSecurityGroupId
        SubnetIds: !Split [",", !ImportValue cfn-utilities:SubnetIds]
      Environment:
        Variables:
          Identity__IdentityServerUri: !Ref IdentityServerUri
          Identity__ClientId: !Ref IdentityClientId
          Identity__ClientSecret: !Ref IdentityClientSecret

Outputs:
  ApplicationResourceArn:
    Value: !GetAtt ApplicationResource.Arn
    Description: ARN of the Brighid Identity Application Custom Resource.
    Export:
      Name: !Sub ${AWS::StackName}:ApplicationResourceArn

  RoleResourceArn:
    Value: !GetAtt RoleResource.Arn
    Description: ARN of the Brighid Identity Role Custom Resource.
    Export:
      Name: !Sub ${AWS::StackName}:RoleResourceArn
