Description: Custom Resources for Brighid Identity.
Transform: AWS::Serverless-2016-10-31
Parameters:
  LambdajectionLayerVersion:
    Type: String
    Description: ARN of the Lambda Layer containing Lambdajection + its dependencies.

  DotnetLayerVersion:
    Type: String
    Description: ARN of the Lambda Layer containing .NET.

  IdentityServerUri:
    Type: String
    Description: URI of the identity server.

  IdentityClientId:
    Type: String
    Description: Client ID of the Discord Application.

  IdentityClientSecret:
    Type: String
    Description: Encrypted Client Secret of the Discord Application.

Resources:
  IdentityCustomResourcesSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Brighid Identity Custom Resources
      VpcId: !ImportValue cfn-utilities:VpcId

  ApplicationResource:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Brighid.Identity.Resources.Application::Brighid.Identity.Resources.Application.Handler::Run
      Runtime: provided.al2
      Timeout: 30
      CodeUri: ../bin/Resources.Application/Release/net5.0/linux-x64/publish/
      MemorySize: 512
      Policies:
        - !ImportValue cfn-utilities:SecretsKeyDecryptPolicyArn
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:dotnet:${DotnetLayerVersion}
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:lambdajection:${LambdajectionLayerVersion}
      VpcConfig:
        SecurityGroupIds:
          - !Ref IdentityCustomResourcesSecurityGroup
        SubnetIds: !Split [",", !ImportValue cfn-utilities:PrivateSubnetIds]
      Environment:
        Variables:
          Identity__IdentityServerUri: !Ref IdentityServerUri
          Identity__ClientId: !Ref IdentityClientId
          Identity__ClientSecret: !Ref IdentityClientSecret

  TestApplication:
    Type: Custom::Application
    DeletionPolicy: Retain
    Properties:
      ServiceToken: !GetAtt ApplicationResource.Arn
      Name: BrighidIdentityApplicationTest1
      Roles:
        - Basic

Outputs:
  ApplicationResourceArn:
    Value: !GetAtt ApplicationResource.Arn
    Description: ARN of the Brighid Identity Application Custom Resource.
    Export:
      Name: !Sub ${AWS::StackName}:ApplicationResourceArn
